on: [pull_request]

name: Continuous integration

jobs:
  create-release:
    needs:
      - check
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: create pre-release
        id: version
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          set -eux
          set -o pipefail
          VERSION="$(env TZ=UTC date +"1.%Y%m%d.$(git rev-list --count origin/main --since "$(date +'%FT00:00:00-12:00')")")"
          echo "Creating release $VERSION"
          echo "::set-output name=version::$VERSION"
          gh release create $VERSION --generate-notes --prerelease --target ${{ github.event.pull_request.head.sha }} --draft

  publish:
    uses: ./.github/workflows/create-artifacts.yml
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}

  promote-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    steps:
      - uses: actions/checkout@v3
      - name: undraft release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release edit ${{ needs.create-release.outputs.version }} --draft=false

  clean-draft:
    runs-on: ubuntu-latest
    needs:
      - create-release
      - publish
    if: ${{ failure() && needs.create-release.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: delete draft release release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          gh release delete ${{ needs.create-release.outputs.version }} --yes

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('ci/cache-version') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
             ${{ runner.os }}-cargo-${{ hashFiles('ci/cache-version') }}-
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      ## Cargo test
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      ## Cargo fmt
      - run: rustup component add rustfmt
      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      ## Cargo clippy
      - run: rustup component add clippy
      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings